# syntax=docker/dockerfile:1

# This is a standalone Dockerfile that does not depend on goreleaser building the binary
# It is NOT the version that is pushed to dockerhub
# FIPS 140-3: native Go Cryptographic Module (GOFIPS140). Based on ld-relay v8 Dockerfile.
FROM golang:1.26.4-alpine3.24 as builder
# See "Runtime platform versions" in CONTRIBUTING.md

RUN apk --no-cache add \
    libc-dev \
 && rm -rf /var/cache/apk/*

ARG SRC_DIR=/go/ld-relay
ARG LD_RELAY_VERSION=9.0.0-rc.5

RUN mkdir -p $SRC_DIR

WORKDIR $SRC_DIR

ADD https://github.com/launchdarkly/ld-relay/archive/refs/tags/v${LD_RELAY_VERSION}.tar.gz /tmp/ld-relay.tar.gz
RUN tar -xzf /tmp/ld-relay.tar.gz -C $SRC_DIR --strip-components=1 \
    && rm /tmp/ld-relay.tar.gz

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOFIPS140=v1.0.0
ENV GOPATH=/go

RUN go build -a -o ldr .

FROM alpine:3.24.1

RUN addgroup -g 1000 -S ldr-user && \
    adduser -u 1000 -S ldr-user -G ldr-user && \
    mkdir /ldr && \
    chown 1000:1000 /ldr

RUN apk add --no-cache \
    ca-certificates \
 && apk add --upgrade libcrypto3 libssl3 \
 && update-ca-certificates \
 && rm -rf /var/cache/apk/*

ARG SRC_DIR=/go/ld-relay

COPY --from=builder ${SRC_DIR}/ldr /usr/bin/ldr

USER 1000

EXPOSE 8030
ENV PORT=8030
ENTRYPOINT ["/usr/bin/ldr", "--config", "/ldr/ld-relay.conf", "--allow-missing-file", "--from-env"]
