server {
    listen 8090;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types application/json text/plain application/xml;

    location / {
        add_header Cache-Control "no-store";
        try_files $uri $uri/ /index.html;
    }

    location /artifacts/ {
        alias /artifacts/;
        autoindex on;
        add_header Cache-Control "no-store";
        add_header X-Content-Type-Options nosniff;
        types {
            application/json json;
            text/plain txt log;
        }
        default_type application/octet-stream;
    }
}
